In [1]:
import qutip as qt
import numpy as np
z0 = qt.basis(2,0)
z1 = qt.basis(2,1)
# Define observables for Alice and Bob.
B1 = (qt.sigmaz() + qt.sigmax()) / np.sqrt(2)
B2 = (qt.sigmaz() - qt.sigmax()) / np.sqrt(2)
A1 = qt.sigmaz()
A2 = qt.sigmax()
# Question 3, part (a)
# Find eigenvalues of Bob's observables.
print('part (a)')
print('eigenvalues of B1: ', B1.eigenenergies())
print('eigenvalues of B2: ', B2.eigenenergies())
print()
# Question 3, part (b)
# Use the standard formula for the CHSH operator for S:
S = qt.tensor(A1,B1) + qt.tensor(A2,B1) + qt.tensor(A1,B2) - qt.tensor(A2,B2)
print('part (b)')
print('CHSH operator: ', S)
print('Eigenvalues of CHSH operator: ', S.eigenenergies())
# The maximum value of the CHSH quantity is the maximum expectation
# value of this operator, which is the maximum eigenvalue.
print('Maximum of CHSH quantity: ', max(S.eigenenergies()))
# This is actually 2*sqrt(2).
print('2*sqrt(2): ', 2*np.sqrt(2))

part (a)
eigenvalues of B1:  [-1.  1.]
eigenvalues of B2:  [-1.  1.]

part (b)
CHSH operator:  Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.41421356  0.          0.          1.41421356]
 [ 0.         -1.41421356  1.41421356  0.        ]
 [ 0.          1.41421356 -1.41421356  0.        ]
 [ 1.41421356  0.          0.          1.41421356]]
Eigenvalues of CHSH operator:  [-2.82842712  0.          0.          2.82842712]
Maximum of CHSH quantity:  2.82842712474619
2*sqrt(2):  2.8284271247461903


In [2]:
# Question 3, part (c)
print('part (c)')
# This gives all the eigenvalues and eigenvectors.
print('All eigenvectors and eigenvalues: ', S.eigenstates())
print()
# This gives all eigenvectors.
print('All eigenvectors: ', S.eigenstates()[1])
print()
# This gives the eigenvector corresponding to the largest eigenvalue, which is the last listed.
print('The eigenvector we want: ', S.eigenstates()[1][-1])
print()
# You will see that this is the equal superposition of 00 and 11, except for an unobservable global phase:
zer = qt.qstate('d')
one = qt.qstate('u')
print('The Bell state: ', (qt.tensor(zer,zer)+qt.tensor(one,one))/np.sqrt(2))
# This means that these measurements will maximise violation of the BEll inequality for the standard Bell state.

part (c)
All eigenvectors and eigenvalues:  (array([-2.82842712e+00,  0.00000000e+00,  1.33226763e-15,  2.82842712e+00]), array([Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
       Qobj data =
       [[ 0.        ]
        [-0.70710678]
        [ 0.70710678]
        [ 0.        ]]                                                    ,
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
       Qobj data =
       [[ 0.        ]
        [-0.70710678]
        [-0.70710678]
        [ 0.        ]]                                                    ,
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
       Qobj data =
       [[ 0.70710678]
        [ 0.        ]
        [ 0.        ]
        [-0.70710678]]                                                    ,
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
       Qobj data =
       [[-0.70710678]
        [ 0.        ]
        [ 0.        ]
        [-