In [1]:
from qutip import *
import numpy as np
import math
z0 = basis(2,0)
z1 = basis(2,1)
x0=(z0+z1)/math.sqrt(2)
x1=(z0-z1)/math.sqrt(2)
st = (tensor(z0,z0)+tensor(z1,z1))/math.sqrt(2)

In [11]:
z00=tensor(z0,z0)
z00*z00.dag()-op00

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [3]:
# First we consider measurements of the observable Z tensor Z.
# Measurement operator for 0,0 measurement result.
op00 = tensor(z0*z0.dag(),z0*z0.dag())
st00 = op00*st
# Probability for 0,0 measurement result.  The outcome for measurement of the observable is 1*1=1.
st00.dag()*st00


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]] Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]] Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.5]]


In [3]:
# Measurement operator for 1,0 measurement result for ZZ.
op10 = tensor(z1*z1.dag(),z0*z0.dag())
st10 = op10*st
# Probability for 1,0 measurement result.  The outcome for measurement of the observable is (-1)*1=1.
st10.dag()*st10

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [4]:
# Measurement operator for 0,1 measurement result for ZZ.
op01 = tensor(z0*z0.dag(),z1*z1.dag())
st01 = op01*st
# Probability for 0,1 measurement result.  The outcome for measurement of the observable is 1*(-1)=-1.
st01.dag()*st01

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [5]:
# Measurement operator for 1,1 measurement result for ZZ.
op11 = tensor(z1*z1.dag(),z1*z1.dag())
st11 = op11*st
# Probability for 1,1 measurement result.  The outcome for measurement of the observable is (-1)*(-1)=1.
st11.dag()*st11

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.5]]

In [6]:
# The measurement operator can be constructed as follows.
op00 - op10 - op01 + op11

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]

In [7]:
# This is the same as if we just directly take the tensor product of Z and Z.
tensor(sigmaz(),sigmaz())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]

In [12]:
# Next we consider measurements of the observable X tensor X.
# Measurement operator for 0,0 measurement result.
op00 = tensor(x0*x0.dag(),x0*x0.dag())
st00 = op00*st
# Probability for 0,0 measurement result.  The outcome for measurement of the observable is 1*1=1.
st00.dag()*st00

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.5]]

In [14]:
# Measurement operator for 1,0 measurement result for XX.
op10 = tensor(x1*x1.dag(),x0*x0.dag())
st10 = op10*st
# Probability for 1,0 measurement result.  The outcome for measurement of the observable is (-1)*1=1.
st10.dag()*st10

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [15]:
# Measurement operator for 0,1 measurement result for XX.
op01 = tensor(x0*x0.dag(),x1*x1.dag())
st01 = op01*st
# Probability for 1,0 measurement result.  The outcome for measurement of the observable is (-1)*1=1.
st01.dag()*st01

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [13]:
# Measurement operator for 1,1 measurement result for XX.
op11 = tensor(x1*x1.dag(),x1*x1.dag())
st11 = op11*st
# Probability for 1,0 measurement result.  The outcome for measurement of the observable is (-1)*1=1.
st11.dag()*st11

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.5]]

In [12]:
# Note that we have perfect correlation between the measurements on the two qubits again in this example.
# The measurement operator can be constructed as follows.
op00 - op10 - op01 + op11

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]

In [13]:
# This is the same as if we just directly take the tensor product of X and X.
tensor(sigmax(),sigmax())

Quantum object: dims = [[2, 2], [2, 2]], shape = [4, 4], type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]